language: python
services:
  - mysql
script: scripts/build.sh
env:
  global:
  - secure: I7+1ip0gef+hr387SLODIv5c+8xjykJuSqQK7QvvLcTQLrSlpMMuBISF/wCNLaA9ZWJKorCaq+JFooWw+7MTNj+ESCNtQPvERwPboxZKrsUnYKsnh/v7zs5V7WlbrlcohbSkhYsUp2zSWWHpWGWrWcAULB4l8I7nQD2JBBhBGqXjpf2fpJRDjD24pIj0tMqYafb1CkrZVShPJqvucs6dBokGcA4byTD1v8aRaVkT2Vs63AmvCZ/KP4+4nWIsXm8D4v2WCOKEvrLn6oYMMrdBpHhZRePw5YMPpj2na4txJv2p7s+coX7b3F0Aew2jLptz0tFUd1FsLFOSDyWVDCbQnGZCkVWhOlhz5Af0dnND2Ym141JfZsQKyZVylFa+KOkg2N+XgevcO1/Zdot8Ar7AgGoOIKoaaw+C4hW8W9MLZ7ndbhLIAh1NOkGuOKVAVySeoWrc77GcPkk2jZf+Y/sx63P2EvaDsTZsRqiJHTFuOfx/nnQd8cNw54kms2FC6Rl8vbT6ebOcQYIlsSOIZmnp/DeeRxvWe2RB9D4uBRBLD7FhQn8R+BeSb0cG7HRDQtKXWaKa2zoDvnCGrJRhwpkXdbl1g0oJW4+CS1Bk9kEvoNpgOWptamCoSx1IjtFBzXLvnNoRAFhsxDSmK/nI989apxYKM2KzsAjhjaTjLUfCEQk=
  - secure: DlTLU2s4Pn1ZCFlYakivAl95b9UDdHmJbf8G3n3NckruCYzhOUyz7PN1GXOAcXxWq7A4xe2t/KJe0ckTWM7rlrigoiT9s/oJ+DRA8LPKV7MyejW26cap/sO1UT7hAx1Gt/EWQuxpRNAOY1U+LzotLeIUuGd2TDKh+CBKZw5Z5jwKfOD+D0eSBIqp+0k15pM59UARwmkHGreW8xokVQ++joy8h6lItNqD7jIj5RWLgxI/JAIB2XOCcUSid+ryf10xcvzm9iJTcrQtzfwfjm31sCxCK3UNjUb7Hv6d4Mo4u4aePcugUmfZN9mAhkz8mW3qdN2wUxuwh0sbKpoTg6ZRoaVdv4bLHj0RFmGVtlhwu1kOKD3ifwIB1Ac183KeHLWJuh5+qS4d8LkQsa06cVVsKdzcVm/fnWWOLtt+sz8WJ9UqOGV3qMEmnD0zJxvGnhEC3cPygjoJStdzXDpwNLSdJKPRVNpTDnWr3MKSPsTGkbTu480F+V7bO9jlmwKmR0MDDCBvBkQyM3cgqac8ygs/HNj2y+YKDkeIrCVU4Is+eXK6U7NrfWDCTaDOTbpfLAlVYD6bXY1+Iv0v00tltMsOw5gSGFNo+49aZkhjBCRjYRDesPCgTQhu6lucpFj2Onx2ldgt44HEGKKZSDohpET8gtiiwYw1vi0nJ3xtp4ZlHi0=
  - secure: zTgt/Ja1iFFRuSDnzNWusQ45wlN0u7MCND2FCRxmopIqpVouN8dIBAA7abHjOkfh88upBOYKfuwkXb7Bh6wM6alXsUBKLgxg5eQvX+HJu9boVdjmkVbs6wcFgnGUC02GrhBH3RFryFqW9bJS3E1Xm2sAnmKlY8nJQBHL4pPmCqsjYA3GK1STj1oeNcIGm9y+Wx+bIftjRy/dCaPttcEtaHVhrRegZGhWC2ly+bHqyBs34dlqiNAWte/SfPqZK5YLJuNvW9hHPsP/tuE65zRD4NLHlC7nioHnR+N8C5NOGBaAZT0ApfCgf5QVW3R+0WXzUApdo10tDPJqnaqY3DNuuvx6yKK0N3HILYrWObm+89sGdM5IMAmuF+p8zdJ2iSPt5wMtVIHbTA9Di0woAGl1yIf0OY2E8XsFWu2OHW5FqzVwr2+XtnbUUb7zD9tOukad94I7sJarmk8fJYEH31OWZIgknOn0z7dvwkCOM/vF7+Ze5Har88SuY1dF6oLO6meqeuoBEPyG2JZKZRvBYf5DdqvGcGdLuBl2wQ1NIcB3Y/S+OzQAE6RpMQQqfRVrW4JOm4oCFWR2apOoBujrcxWDBvqPno45FpaVCngvA76AL+qvjngnqoTRrnoU5Gn1JzugeGUQOynPlQB1tzKAgB8MvaARACiBA7PRbBdfzXMuVkY=
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- chmod 600 /tmp/deploy_rsa
- eval "$(ssh-agent -s)"
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  script: scripts/deploy.sh
  skip_cleanup: true
  on:
     branch: master
