language: python
env:
  global:
  - secure: h+r1hELpLuTLAqEcsMuiUSl31JqyZhWp9IxHV9El2O1vV0ED6ooikYP5Na1AylbIKXALLh9LkXAJX2ngyRYGj+Snu6pNiJx1a80mfPCrpOm6wlNGPvNzUBA8xgT8FZtMHT4s2OVOFG/6G7QPMttASttg0AIcM7kOLwBaGIezE5OBLdXVJbcMLP+6vtf93RojTscs/Yq1YFZRILt/PUbfalk2K+ANkxyS6Uq7Q3XeUmrkgP3o9uw+RtiP2NbHoGZbSXTxhiCbvquHu7sdp75GN8vC8oPubOyTaQZmYv+AkOA2g1tBnNR2GqeYyKmtnUfF3avOo1/4bnW6f+k1Hr1+04YTIhiLIW87riqBzEjYMhpxsFt6s57IdPIzhK8cc4SftFJr1jYaRfsOgsy//bbkknTPNP0oUcoF8UCrGw1LiSwq2l0r9v2v1KtQe2a9KiTBswiSoHhn9kvIx9ZuDCxilQrAfMvt1E07wo4XzoreN5eRnM3Xpr2Z9RgrZ6NeNnC9F7xkaUHgPOMRRI1LLaacgUuP77nDHpVLtK9w3Mm2ZDf7nVv9Lu9mVzSOLBbFWv/t03f7chWupNopO0hCPd61fzFNZ6yf9gfFCFw+mPzOvWa8nHYrEe+OQFJlJGMgUFl0GKSJq/bqY1vR+1FXBdaAOS/wQCbbuIlgb3RjgeoacBg=
  - secure: AMhivHVNa9vqhzSlP+keaszsVL9dPV7ObzZnub16Nz1NK3TaPrG+Dx5+WkZ23PSZi5/LVofsetP1VCzLRJImCKVS9E1aGbFybYt1Zk9Z0WKqXXdMhO9bVL0frmHPg7OL3nQxlbSSimetL7lmcYAgBa89GejyAacBBuQdI0e3G2UQkZYFxa9iPWpZeN8S207uhZKa/jfGPjWfaa3cJ02qqKSuXMbwuHqFby4pPQtmdrJGME2g36tnIpSnOkDT8ww5DI86+cKN1fj8a8uyo9zERctZYo+IhSXmgWwjceNYR0T+dP26f26NOr2Bhvbps0vRLLWfcM2VDXAc97GSSwhtK7OjHBJbI+72nxQrjv8uF8YrwsLMaVBabOquSA5xV8KZZyyy1Gv0egU338J8cIEWp0aiZk3+SKFzq3G5hPyDf4gXjpTmtrx9gxUUq2PyKmUq63MCZBBBiu2i+8+yHiorD77OigjEzXc65XEoY4LUBsyFWIXKfk6wzMnC7ZCYcoGU6FtltXH9JUQ4RLBrM0kyncreMZl1lwTzrYx7oGGFxUb1qlOFJ4JNur/NA5be3aykZFkxSA5NucGFWxV2evAUEu++BZM5T0NiEFiD0XlgbXU4COSGZ1vyNaMqsth1cttLiHnoM0+hJw3qfqP8bOZefYFhFETIkH4VW9UxE4O5Izo=
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- chmod 600 /tmp/deploy_rsa
- eval "$(ssh-agent -s)"
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  script: scripts/deploy.sh
  skip_cleanup: true
