# Generated by Django 3.1.2 on 2020-11-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rounds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_round', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='famousnames',
            name='round_number',
            field=models.IntegerField(default=1),
        ),
    ]
